apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dms
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  class: nginx
  forceIngressClass: false
spec:
  rules:
    - http:
        paths:
          - path: /server(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 3030
          - path: /client(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 3000
