apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server_production:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_DB_CONNECTION
              value: mongodb+srv://Cloak2656:Pried3-Circling-Doctrine@cluster0.5cythdj.mongodb.net/deadmansswitch?authSource=admin&replicaSet=atlas-nkjaoa-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true
            - name: PORT
              value: '3030'
