apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server_production:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3030
          env:
            - name: MONGO_DB_CONNECTION
              value: mongodb://root:password1234@deadmansswitch-mongodb-arbiter-headless:27017?directConnection=true&ssl=false&authSource=admin&w=1

            - name: PORT
              value: '3030'
