apiVersion: apps/v1
kind: Deployment
metadata:
  name: dead-mans-switch-be
spec:
  selector:
    matchLabels:
      app: dead-mans-switch-be
  replicas: 2
  template:
    metadata:
      labels:
        app: dead-mans-switch-be
    spec:
      containers:
        - name: dead-mans-switch-be
          image: iamhunter/dead-mans-switch-be
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
