import { InputType, Int, Field } from '@nestjs/graphql';

@InputType()
export class CreateVaultInput {
  @Field({ description: 'JWT Generated by Google Login' })
  googleCredential: string;

  @Field({ description: 'Vault Data' })
  readonly data: string;
}
