import { Field, InputType, PartialType } from '@nestjs/graphql';
import { GetVaultInput } from './get-vault.input';

@InputType()
export class RemoveVaultInput extends PartialType(GetVaultInput) {
  @Field({ description: 'JWT Generated by Google Login' })
  googleCredential: string;
}
